# --- !Ups

create table "continent" (
  "continentId" bigint generated by default as identity(start with 1) not null primary key,
  "continentName" varchar not null
);

create table "country" (
    "countryId" bigint not null primary key,
    "countryName" varchar not null,
    "continentId" bigint not null
);

create table "city" (
    "cityId" bigint not null primary key,
    "cityName" varchar not null,
    "countryId" bigint not null
);

# --- !Downs

drop table "continent" if exists;

drop table "country" if exists ;

drop table "city" if exists ;
